#server:
#  port: 9527
spring:
 cloud:
    gateway:
      routes:
        - id: config
#          uri: http://localhost:8001
          uri: lb://nacos-config-client
          predicates:
            - Path=/config/**
#        - id: payment_routh2
##          uri: http://localhost:8001
#          uri: lb://cloud-payment-service
#          predicates:
#            - Path=/payment/lb/**
#            - After=2022-07-19T15:23:33.188571900+08:00[Asia/Shanghai]
      discovery:
        locator:
          enabled: true  #开启从注册中心动态生成路由的功能，用微服务名进行路由
